gText_Birch_Welcome::
	.string "... ... ... ... ... ... ...\p"
	.string "...Hello? ...Hello...?\p"
	.string "...Is anyone there?\p"
	.string "Wait- got it.  Well hi there!\n"
	.string "I'm MICHAEL.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Listen, I could really use your help.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Things have gone a little bit...\n"
	.string "...let's say ''haywire.''\p"
	.string "You seem like the kind of person\n"
	.string "I can depend on, but, well...\l"
	.string "This is serious business!\p"
	.string "Look, I'll just send you in\n"
	.string "and see what you can do from here.\p"
	.string "If you can make your way through\n"
	.string "this simulation, then maybe...\p"
	.string "...Just maybe, you might be the\n"
	.string "one who can help me.  Deal?\p"
	.string "Oh, and if you're worried,\n"
	.string "I'll send my sister in after you.\l"
	.string "Her name is JOVI.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
