gText_Birch_Welcome::
	.string "... ... ... ... ... ... ...\p"
	.string "...Hello? ...Hello...?\p"
	.string "...Is anyone there?\p"
	.string "Wait- got it.  Well, hi there!\n"
	.string "I'm MICHAEL.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Listen, I could really use your help.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Things have gone a little bit...\n"
	.string "...let's say ''haywire.''\p"
	.string "You seem like the kind of person\n"
	.string "I can depend on, but, well...\l"
	.string "This is serious business!\p"
	.string "Look, I'll just send you in\n"
	.string "and see what you can do from here.\p"
	.string "If you can make your way through\n"
	.string "this simulation, then maybe...\p"
	.string "...Just maybe, you might be the\n"
	.string "one who can help me.  Deal?\p"
	.string "Oh, and if you're worried,\n"
	.string "I'll send my sister in after you.\l"
	.string "Her name is JOVI.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "{PLAYER}{KUN}, I'm pleased to make\n"
	.string "your acquaintance.  Now if you'll\l"
	.string "excuse me...\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "I have some tasks of a quite\p"
	.string "serious nature I must attend to.\n"
	.string "So sorry!\p"
	.string "If it's any consolation, JOVI'\n"
	.string "is a lot better at this than I am.\l"
	.string "She'll get you sorted out.\p"
	.string "Do your best to find her, and\n"
	.string "show me what you've really got!\p"
	.string "$"
